### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Erianafranky**
Added some more features

### CODE REVIEW

**Comment by Nerldy** [comment]
I like the about page pic

**Comment by Nerldy** [comment]
Good job. Only thing I may add is maybe your commit messages could b a little more descriptive

**Comment by faustineomuya** [comment]
good job. @Erianafranky. We're heading in the right direction

**Comment by Nerldy** [comment]
Mind adding a screenshot of your design?

**Comment by ezrqnkemboi** [comment]
This is a good work.

**Pull request merged**
